### ISSUE TITLE
Document has not been applied to structure yet when calling .getContent() on a article view which has a smartcontent.

### ISSUE THREAD

**Issue by marcostastny** [sulu/SuluArticleBundle#335] opened 2018-06-28 14:08 UTC
| Q | A
| --- | ---
| Bug? | Yes
| New Feature? | no
| SuluArticleBundle Version | 1.0.0-RC6
| Sulu Version | 1.6.16

#### Actual Behavior

When I add a smart content (in this example the block type windmill.xml or offer.xml
) to a article it will break smart_contents linking to this article. This happens as i call item.content.content (which is equivalent to item.cotnent.getContent(), as the content is of Class ArticleTypeDocument).
 
#### Expected Behavior

It should still work, even though there is a smartcontent.

#### Steps to Reproduce

1. Take given xml and add a windmill or offer block in backend, does not needs to be filled with data.
2. Take given template xml and try to access content on article element.

#### Article Properties needed

```
<property name="magazineSmartContent" type="smart_content">
    <meta>
        <title lang="de">Smart Content</title>
        <title lang="en">Smart Content</title>
    </meta>

    <params>
        <param name="provider" value="articles"/>
        <param name="properties" type="collection">
            <param name="excTitle" value="excerpt.title"/>
            <param name="excDescription" value="excerpt.description"/>
            <param name="excImages" value="excerpt.images"/>
            <param name="headerTitle" value="headerTitle"/>
            <param name="headerSubtitle" value="headerSubtitle"/>
            <param name="headerDescription" value="headerDescription"/>
        </param>
    </params>
</property>
```

## or

```
<property name="title" type="text_line">
    <meta>
        <title lang="de">Titel</title>
        <title lang="en">Title</title>
    </meta>
</property>

<property name="smartContent" type="smart_content">
    <meta>
        <title lang="de">Smart Content</title>
        <title lang="en">Smart Content</title>
    </meta>

    <params>
        <param name="provider" value="content"/>
        <param name="properties" type="collection">
            <param name="excTitle" value="excerpt.title"/>
            <param name="headerTitle" value="headerTitle"/>
            <param name="headerDescription" value="headerDescription"/>
            <param name="excDescription" value="excerpt.description"/>
            <param name="excImages" value="excerpt.images"/>
            <param name="amountNights" value="headerAmountNights"/>
            <param name="price" value="headerPrice"/>
        </param>
    </params>
</property>
```

#### Showing at template.

```
<property name="magazineSmartContent" type="smart_content">
    <meta>
        <title lang="de">Smart Content</title>
        <title lang="en">Smart Content</title>
    </meta>

    <params>
        <param name="provider" value="articles"/>
        <param name="properties" type="collection">
            <param name="excTitle" value="excerpt.title"/>
            <param name="excDescription" value="excerpt.description"/>
            <param name="excImages" value="excerpt.images"/>
            <param name="headerTitle" value="headerTitle"/>
            <param name="headerSubtitle" value="headerSubtitle"/>
            <param name="headerDescription" value="headerDescription"/>
        </param>
    </params>
</property>
```

#### Called in html like

```
{% for item in block.magazineSmartContent %}
    {% set title = item.excerpt.title|default(item.content.content.excTitle|default(item.content.content.headerTitle|default(item.title))) %}
{% endfor %}
```

**Comment by niklasnatter** [comment] 2020-12-21 10:29
Hey,
i just tried to reproduce this with Sulu 2.2.2 and SuluArticleBundle 2.2.2. I used the following templates, but could not reproduce the error. Therefore I am going to close this. Please feel free to create a new issue if the problem still occurs for you when using an up-to-date version of the bundle!

article.xml
```xml
<block name="smartBlocks" default-type="editor" minOccurs="0">
    <meta>
        <title lang="en">Content</title>
        <title lang="de">Inhalte</title>
    </meta>

    <types>
        <type name="editor">
            <meta>
                <title lang="en">Editor</title>
                <title lang="de">Editor</title>
            </meta>
            <properties>
                <property name="pages" type="smart_content">
                    <meta>
                        <title lang="de">Smart Content</title>
                        <title lang="en">Smart Content</title>
                    </meta>

                    <params>
                        <param name="provider" value="pages"/>

                        <param name="properties" type="collection">
                            <param name="excTitle" value="excerpt.title"/>
                            <param name="excDescription" value="excerpt.description"/>
                            <param name="excImages" value="excerpt.images"/>
                            <param name="title" value="title"/>
                        </param>
                    </params>
                </property>
            </properties>
        </type>
    </types>
</block>
```

article.html.twig
```twig
{{ dump(content.smartBlocks[0].articleSmartContent) }}
```

page.xml
```xml
<block name="smartBlocks" default-type="editor" minOccurs="0">
    <meta>
        <title lang="en">Content</title>
        <title lang="de">Inhalte</title>
    </meta>

    <types>
        <type name="editor">
            <meta>
                <title lang="en">Editor</title>
                <title lang="de">Editor</title>
            </meta>
            <properties>
                <property name="articles" type="smart_content">
                    <meta>
                        <title lang="en">Articles</title>
                        <title lang="de">Artikel</title>
                    </meta>

                    <params>
                        <param name="provider" value="articles"/>

                        <param name="excTitle" value="excerpt.title"/>
                        <param name="excDescription" value="excerpt.description"/>
                        <param name="excImages" value="excerpt.images"/>
                        <param name="title" value="title"/>
                    </params>
                </property>
            </properties>
        </type>
    </types>
</block>
```

page.html.twig
```twig
{{ dump(content.smartBlocks[0].articles) }}
{{ dump(content.smartBlocks[0].articles[0].content.content.title) }}
{{ dump(content.smartBlocks[0].articles[0].content.view.title) }}
```

**Closed by niklasnatter** 2020-12-21 10:29 UTC
