### ISSUE TITLE
error on php bin/console ongr:es:index:create apparently conflict with the Elastic Search Version

### ISSUE THREAD

**Issue by alejandrofloresm** [sulu/SuluArticleBundle#297] opened 2018-01-22 03:39 UTC
| Bug? | yes
| SuluArticleBundle Version | 0.7.1
| Sulu Version | 1.6.13
| Elastic Search Version| 6.1.2

#### Actual Behavior

Throws the following error when running `php bin/console ongr:es:index:create` 

`{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [changer_contact_id]"}],"type":
  "mapper_parsing_exception","reason":"Failed to parse mapping [article]: No handler for type [string] declared on field [changer_contact_id]","cause
  d_by":{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [changer_contact_id]"}},"status":400}`

#### Expected Behavior

Shouldn't be throwing the error and set correctly the index

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by wachterjohannes** [comment] 2018-01-22 07:28
@alejandrofloresm the current implementation of article-bundle seems not to be ready for elasticsearch `^6.0` and won't be with `1.0` on the first look. the problem is the ONGRElasticsearchBundle which is not able to handle `^2.4`, `^5.0` and `^6.0` - maybe we find a way to introduce this in one of the minor releases of `1.x`. if this is not possible we can only update with the 2.0 version of the article-bundle when we drop the `2.4` compatibility.

**Comment by EssamKhaled** [comment] 2018-02-19 09:42
unfortunately same here :(

**Comment by wachterjohannes** [comment] 2018-02-19 10:33
@EssamKhaled you have to downgrade your elasticsearch to 5.* which works quite well.

**Comment by wachterjohannes** [comment] 2018-04-12 08:30
there is a related ticket for this https://github.com/sulu/SuluArticleBundle/issues/304

**Comment by niklasnatter** [comment] 2020-12-21 09:17
Thanks for reporting - this was fixed with #433

**Closed by niklasnatter** 2020-12-21 09:17 UTC
